Capstone Project Setup
pushkar1995/capstone-project1.0 pull request #1
Opened 2023-07-04 09:48 UTC by pushkar1995

- Add basic requirements for repo setup
- Add basic HTML and CSS according to the design

2023-07-06 20:19 UTC, Shisui6 requested changes
Hi @pushkar1995, 

# Requires Changes 🍀
You have done a great job so far!👏👏
You still need to work on a few issues before moving on to the next project, but you're almost there🪲!

## Highlights🎯
- Descriptive PR title and summary ✅
- Follows Github flow ✅
- Good commit messages ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 🪶
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

You can also consider the following:

N/A

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-06 20:19 UTC, Shisui6 commented on index.html
> +                        <div><a class="about-h4" href="/pages/about.html">About</a></div>
Nice job deploying your project using github pages. However, the link to your about page is not working as it leads to a 404 page. Please go through your project and ensure that all links work as expected

2023-07-06 20:19 UTC, Shisui6 commented on index.html
> +                <div class="activity-icon"><img src="JM-Images/ActivitiesIcons/HikingIcon.png"></div>
Kindly make sure all the images in your website have an alt attribute to improve accessibility🙏

2023-07-06 20:19 UTC, Shisui6 commented on index.html
> +                        </div>
Currently your website is missing a lot of the styles from the behance design guidelines. Please go through all the points listed below and update your website to conform to the behance design:

Your design:
<img width="434" alt="image" src="https://github.com/pushkar1995/capstone-project1.0/assets/37116322/74642cea-11db-4edd-8486-1ba0b56498bc">

Behance design:
<img width="453" alt="image" src="https://github.com/pushkar1995/capstone-project1.0/assets/37116322/d17cfd3b-4fb5-4dcc-8112-2fb3d6194977">


- Kindly update the main color of your website to be the same color used in the behance design. The main color used is `#fe5038`
- Currently there is a horizontal scroll in the desktop version of your website. Please identify the element causing it and remove it
- Kindly increase the font size and weight of the main title in the headline section  to match the behance design
-Kindly add some padding to each card in the mobile version of the main program section and align the text of each text to be in line with the behance design
- Kindly remove the activities and contact section. There are not present in the behance design
- Kindly make sure that each picture of your featured speakers are the same size
- Kindly add the partner section present in the behance design
- Kindly update the footer in your mobile version to have the logo aligned to the left and the text aligned to the right

2023-07-06 20:19 UTC, Shisui6 commented on pages/about.html
> +                            <h4><a href="#activities">Main Activities</a></h4>
Currently, your about page does not represent the behance design at all. Please update your about page to include all the elements present in the behance design. Please make sure to respect the color scheme, typography and layout of each element

Your design:
<img width="435" alt="image" src="https://github.com/pushkar1995/capstone-project1.0/assets/37116322/142c1ec0-79ba-4219-9d5b-9385e5ee36a6">

Behance design:
<img width="527" alt="image" src="https://github.com/pushkar1995/capstone-project1.0/assets/37116322/aaaad476-f35c-4421-8ea9-a2a86883d0f3">

2023-07-07 13:27 UTC, Cabraham1 approved these changes
Hi @pushkar1995 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-07 15:30 UTC, merged